name: Automated Preprocessing Pipeline

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    name: Run Data Preprocessing (Step 1-8)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn matplotlib seaborn

      - name: Run automate_Muhammad_Syaiful.py
        run: |
          python preprocessing/automate_Muhammad_Syaiful.py --input heart_raw/heart_raw.csv --output_dir preprocessing/heart_preprocessing

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/heart_preprocessing/
